### ISSUE TITLE
Gitlab commit status api

### ISSUE THREAD

**Issue by andreimc** [kubebuild/agent#1]
### Tasks for status api

- [x] Add https://github.com/xanzy/go-gitlab as a gitlab client
- [x] Oauth for gitlab.com is this PRIVATE-TOKEN the same thing or the api token?
- [x] Ouath provider in app ?
- [x] API token for custom installs ? PRIVATE-TOKEN
- [x] UI for adding api key and url (github_hosted) ? provider
- [x] SendNotification from agent - code split base on client -- if gitlab send to gitlab

**Comment by andreipetrescu95** [comment]
Some stuff about how Jenkins is integrated with GitLab:

https://github.com/jenkinsci/gitlab-plugin
https://docs.gitlab.com/ee/integration/jenkins.html
